### - command is "###"
### REad the entity set defined in the catalog

http://localhost:4004/odata/v4/CatalogService

###Metadata and the entity set call
http://localhost:4004

### read the metadata of the catalog
http://localhost:4004/odata/v4/CatalogService/$metadata


###REad the entity set data
http://localhost:4004/odata/v4/CatalogService/businesspartner

###Create Entry - Post call
POST  http://localhost:4004/odata/v4/CatalogService/businesspartner
Content-Type: application/json

  {
      "ADDRESS_GUID_NODE_KEY": "74867AD200E41EDBA5D8B06885992053",
      "BP_ID": "74867AD200E41EDBA5D8B06885992053",
      "BP_ROLE": "1",
      "COMPNAY_NAME": "PwC",
      "EMAIL": "dhivya.ganesan@pwc.com",
      "FAX": "622734004",
      "MOBILE": "622734567",
      "NODE_KEY": "74867AD200E41EDBA5D8B06885A56053",
      "WEB": "http://www.sap.com"
    }

###Update the entry - PATCH CALL
PATCH  http://localhost:4004/odata/v4/CatalogService/businesspartner/74867AD200E41EDBA5D8B06885A56053
Content-Type: application/json

  {
  "COMPNAY_NAME": "PwC AC"
    }

###Get - employee DEtails
http://localhost:4004/odata/v4/CatalogService/EmployeeDetails/02BD2137-0890-1EEA-A6C2-BB55C19787FC

###CREATE Employee

###Get - employee DEtails
POST http://localhost:4004/odata/v4/CatalogService/EmployeeDetails
Content-Type: application/json

   {
      "Currency_code": "USD",
      "ID": "02BD2137-0890-1EEA-A6C2-BB55C19787FC",
      "accountNumber": "111222333",
      "bankId": "510000655",
      "bankName": "My Bank of Antioch",
      "email": "sally.spring@itelo.info",
      "gender": "F",
      "language": "E",
      "loginName": "GD",
      "nameFirst": "Dhivya",
      "nameInitials": null,
      "nameLast": "Spring",
      "nameMiddle": null,
      "phone": "+1 224 374 524",
      "salaryAmount": "55549.00"
    }


 


###update - employee DEtails

PATCH http://localhost:4004/odata/v4/CatalogService/EmployeeDetails/02BD2137-0890-1EEA-A6C2-BB55C19787FC
Content-Type: application/json

   {
      "salaryAmount": "1555549.00"
    }

###Get - employee DEtails
PATCH http://localhost:4004/odata/v4/CatalogService/ProductDet/74867AD200E41EDBA5D8B06B26EB4052
Content-Type: application/json

{
  "HEIGHT": "3.00"
  
  }


###Get the purchase Order details
http://localhost:4004/odata/v4/CatalogService/PODetails

###Get the PO details for a node
http://localhost:4004/odata/v4/CatalogService/PODetails('74867AD200E41EDBA5D8B0C98DC28052')

###Call Custom Action to update the Gross Amount and net amount
POST http://localhost:4004/odata/v4/CatalogService/PODetails('74867AD200E41EDBA5D8B0C98DC28052')/CatalogService.increasedprice
Content-Type: application/json

{

}


###call Custom Function to get the Purchase Order with largest Gross Amount

GET  http://localhost:4004/odata/v4/CatalogService/PODetails('74867AD200E41EDBA5D8B0C98DC28052')/CatalogService.largestorder()


###Get employee Details
http://localhost:4004/odata/v4/CatalogService/EmployeeDetails

###Custom Bound Action to create the Employee details with generatd UUID
POST http://localhost:4004/odata/v4/CatalogService/createEmployee
Content-Type: application/json

   {
    //UUID is not mentioned, its autogenerated int .js file
      "accountNumber": "111222333",
      "bankId": "510000655",
      "bankName": "DOGGY BANK",
      "email": "sally.spring@itelo.info",
      "gender": "F",
      "language": "E",
      "loginName": "DOGGY",
      "nameFirst": "Sally",
      "nameInitials": null,
      "nameLast": "Spring",
      "nameMiddle": null,
      "phone": "+1 224 374 524",
      "salaryAmount": "55549.00"
    }


###unbounded action to get the product details for the input currency code
GET http://localhost:4004/odata/v4/CatalogService/getProducts('EUR')